language: c

os:
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libgd ; fi

notifications:
  email:
    - bob@rud.is
  irc:
    channels:
      - "irc.rud.is#builds"
    nick: travisci